export const pageStyles = {
  heading: {
    fontSize: 26,
    fontWeight: 700,
    color: "#111",
    lineHeight: 1.3,
    margin: 0,
  },
  subheading: {
    fontSize: 13,
    color: "#888",
    marginTop: 8,
    marginBottom: 0,
  },
  errorBox: {
    marginTop: 16,
    padding: "10px 14px",
    backgroundColor: "#fff0f0",
    border: "1px solid #ffcccc",
    borderRadius: 6,
    fontSize: 13,
    color: "#cc0000",
  },
  successBox: {
    marginTop: 16,
    padding: "10px 14px",
    backgroundColor: "#f0fff8",
    border: "1px solid #b3f0d4",
    borderRadius: 6,
    fontSize: 13,
    color: "#0a6640",
  },
  buttonRow: {
    display: "flex",
    gap: 12,
  },
  btnPrimary: {
    flex: 1,
    padding: "13px 0",
    backgroundColor: "#2979FF",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    transition: "background-color 0.15s",
    fontFamily: "inherit",
  },
  btnPrimaryFull: {
    width: "100%",
    padding: "13px 0",
    backgroundColor: "#2979FF",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    transition: "background-color 0.15s",
    fontFamily: "inherit",
  },
  btnOutline: {
    flex: 1,
    padding: "13px 0",
    backgroundColor: "#ffffff",
    color: "#2979FF",
    border: "1.5px solid #2979FF",
    borderRadius: 6,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    transition: "background-color 0.15s",
    fontFamily: "inherit",
  },
  linkButton: {
    background: "none",
    border: "none",
    color: "#2979FF",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    padding: 0,
    fontFamily: "inherit",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    fontSize: 13,
    color: "#444",
    cursor: "pointer",
  },
};
